 version: "3"

 services:
     database:
         image: mysql
         container_name: test_db_5
         environment:
               - MYSQL_DATABASE=testdb
               - MYSQL_ROOT_HOST=%
               - MYSQL_ROOT_PASSWORD=1234
         command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
         ports:
               - 3306:3306
         volumes:
               - /home/revision/docker_spring/database/testdb/:/var/lib/mysql
         networks:
               - test_network_02

     application:
         build: .
         restart: always
         ports:
               - 80:8080
         depends_on:
               - database
         container_name: app_test01
         environment:
             SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/testdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
             SPRING_DATASOURCE_USERNAME: root
             SPRING_DATASOURCE_PASSWORD: 1234
         networks:
               - test_network_02

 networks:
     test_network_02: